
export const Features = () => {
	return (
		<section className={'bg-white dark:bg-gray-900'}>
			<div className={'container px-6 py-10 mx-auto'}>
				<h1 id={"features"} className={'text-3xl font-semibold text-center text-gray-800 capitalize lg:text-4xl dark:text-white'}>explore our <br></br> awesome <span className={'text-blue-500'}>Features</span></h1>

				<div className={'grid grid-cols-1 gap-8 mt-8 xl:mt-12 xl:gap-16 md:grid-cols-2 xl:grid-cols-3'}>
					<div className={'flex flex-col items-center p-6 space-y-3 text-center bg-gray-100 rounded-xl dark:bg-gray-800'}>
						<span className={'inline-block p-3 text-blue-500 bg-blue-100 rounded-full dark:text-white dark:bg-blue-500'}>
							<svg xmlns="http://www.w3.org/2000/svg" className={'w-6 h-6'} fill="none" viewBox="0 0 24 24" stroke="currentColor">
								<path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 5H7a2 2 0 00-2 2v12a2 2 0 002 2h10a2 2 0 002-2V7a2 2 0 00-2-2h-2M9 5a2 2 0 002 2h2a2 2 0 002-2M9 5a2 2 0 012-2h2a2 2 0 012 2m-3 7h3m-3 4h3m-6-4h.01M9 16h.01" />
							</svg>
						</span>

						<h1 className={'text-2xl font-semibold text-gray-700 capitalize dark:text-white'}>Sustainable Nutrition</h1>

						<p className={'text-gray-500 dark:text-gray-300'}>
							More than a third of all man-made greenhouse gas emissions are generated by food systems. Tamabara is on a mission to make nutrition more sustainable. We achieve this by incentivizing people to food with a smaller carbon footprint through a unique combination of education and gamification.
						</p>
					</div>

					<div className={'flex flex-col items-center p-6 space-y-3 text-center bg-gray-100 rounded-xl dark:bg-gray-800'}>
						<span className={'inline-block p-3 text-blue-500 bg-blue-100 rounded-full dark:text-white dark:bg-blue-500'}>
							<svg xmlns="http://www.w3.org/2000/svg" className={'w-6 h-6'} fill="none" viewBox="0 0 24 24" stroke="currentColor">
								<path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 6V4m0 2a2 2 0 100 4m0-4a2 2 0 110 4m-6 8a2 2 0 100-4m0 4a2 2 0 110-4m0 4v2m0-6V4m6 6v10m6-2a2 2 0 100-4m0 4a2 2 0 110-4m0 4v2m0-6V4" />
							</svg>
						</span>

						<h1 className={'text-2xl font-semibold text-gray-700 capitalize dark:text-white'}>CarbonScore</h1>

						<p className={'text-gray-500 dark:text-gray-300'}>
							Tamabara is able to calculate the carbon footprint of any food product with a barcode. We do this by calculating the CO2 emissions of every ingredient of a scanned product and combining it into a product-specific CarbonScore that represents the carbon footprint of the product as a value between 0 (bad) and 100 (good).
						</p>
					</div>

					<div className={'flex flex-col items-center p-6 space-y-3 text-center bg-gray-100 rounded-xl dark:bg-gray-800'}>
						<span className={'inline-block p-3 text-blue-500 bg-blue-100 rounded-full dark:text-white dark:bg-blue-500'}>
							<svg xmlns="http://www.w3.org/2000/svg" className={'w-6 h-6'} fill="none" viewBox="0 0 24 24" stroke="currentColor">
								<path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M5 3v4M3 5h4M6 17v4m-2-2h4m5-16l2.286 6.857L21 12l-5.714 2.143L13 21l-2.286-6.857L5 12l5.714-2.143L13 3z" />
							</svg>
						</span>

						<h1 className={'text-2xl font-semibold text-gray-700 capitalize dark:text-white'}>Gamification</h1>

						<p className={'text-gray-500 dark:text-gray-300'}>
							To make sustainable nutrition more fun - especially for young people - we combined the CarbonScore feature with a virtual pet that can be fed with the products that got scanned. Based on how environmental friendly the product is, the virtual pet will appreciate or disapprove of the snack. A total score of all scanned products demonstrates how sustainable the users eating habits are.
						</p>
					</div>
				</div>
			</div>
		</section>
	)
}