import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { Team } from '../components/team'
import { Features } from '../components/features'
import { Footer } from '../components/footer'
import { Screenshots } from '../components/screenshoots'
import { Video } from '../components/video'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Tamabara</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Video/>
      <Screenshots/>
      <Features/>
      <Team/>
      <Footer/>
    </div>
  )
}
